[tool.ruff]
line-length = 120
target-version = "py311"
extend-exclude = [
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".tox",
    ".venv",
    "_build",
    "buck-out",
    "build",
    "dist",
    "migrations",
]

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = []

[tool.ruff.lint.per-file-ignores]
"apps/authentication/patches/jwt_version.py" = ["E501"]
"apps/executions/management/commands/populate_real_data.py" = ["E501", "F841"]
"apps/executions/tasks.py" = ["E501"]
"apps/integrations/admin.py" = ["E501"]
"apps/workflows/management/commands/add_template_nodes.py" = ["E501"]
"apps/workflows/management/commands/populate_workflow_templates.py" = ["E501"]
"apps/workflows/tasks.py" = ["E501"]
"orchestrix/settings.py" = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "orchestrix.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
addopts = "--reuse-db --nomigrations"
